# Generated by Django 4.2.4 on 2023-08-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_persons_account_balance_alter_persons_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
