# Generated by Django 4.2.4 on 2023-08-17 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_persons_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
