# Generated by Django 4.2.1 on 2024-04-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_transactions_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('data', models.CharField(max_length=1000)),
            ],
        ),
    ]
